# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
     guzzle_parameters:
          base_uri: "http://127.0.0.1:3030"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     guzzle_client:
         class: GuzzleHttp\Client
         arguments: [%guzzle_parameters%]
